### ISSUE TITLE
Invalid byte sequence in UTF-8 (Windows)

### ISSUE THREAD

**Issue by Dalazen** [sds/overcommit#795] opened 2022-08-18 14:30 UTC
```
invalid byte sequence in UTF-8

C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/overcommit-0.59.1/lib/overcommit/utils/file_utils.rb:67:in `win32_symlink?'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/overcommit-0.59.1/lib/overcommit/utils/file_utils.rb:27:in `symlink?'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/overcommit-0.59.1/lib/overcommit/utils.rb:271:in `broken_symlink?'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/overcommit-0.59.1/lib/overcommit/hook_context/helpers/stash_unstaged_changes.rb:65:in `block in store_modified_times'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/overcommit-0.59.1/lib/overcommit/hook_context/helpers/stash_unstaged_changes.rb:64:in `each'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/overcommit-0.59.1/lib/overcommit/hook_context/helpers/stash_unstaged_changes.rb:64:in `store_modified_times'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/overcommit-0.59.1/lib/overcommit/hook_context/helpers/stash_unstaged_changes.rb:11:in `setup_environment'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/overcommit-0.59.1/lib/overcommit/hook_runner.rb:42:in `block in run'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/overcommit-0.59.1/lib/overcommit/interrupt_handler.rb:86:in `isolate_from_interrupts'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/overcommit-0.59.1/lib/overcommit/hook_runner.rb:30:in `run'
.git/hooks/pre-commit:87:in `<main>'
Report this bug at https://github.com/sds/overcommit/issues
```

Overcommit settings:

```
PreCommit:
  RuboCop:
    enabled: true
```

Also tried to disable symlink but still not working

```
PreCommit:
  BrokenSymlinks:
    enabled: false
  RuboCop:
    enabled: true
```

Apparently it works just fine when running `overcommit -r` but still not working when trying to commit

**Comment by sds** [comment] 2022-08-20 20:26
Looks like a duplicate of #791. Would welcome a contribution to fix.

**Closed by sds** 2022-08-20 20:26 UTC
Labels: duplicate
